<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Testing_table.php');
	include_once(__DIR__ . '/Testing_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Testing_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Testing_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Testing_table`.`id`" => "id",
		"`Testing_table`.`name`" => "name",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Testing_table`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Testing_table`.`id`" => "id",
		"`Testing_table`.`name`" => "name",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Testing_table`.`id`" => "ID",
		"`Testing_table`.`name`" => "Name",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Testing_table`.`id`" => "id",
		"`Testing_table`.`name`" => "name",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Testing_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Testing_table_view.php';
	$x->TableTitle = 'Testing table';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Testing_table`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Name', ];
	$x->ColFieldName = ['name', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Testing_table_templateTV.html';
	$x->SelectedTemplate = 'templates/Testing_table_templateTVS.html';
	$x->TemplateDV = 'templates/Testing_table_templateDV.html';
	$x->TemplateDVP = 'templates/Testing_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Testing_table_init
	$render = true;
	if(function_exists('Testing_table_init')) {
		$args = [];
		$render = Testing_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Testing_table_header
	$headerCode = '';
	if(function_exists('Testing_table_header')) {
		$args = [];
		$headerCode = Testing_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Testing_table_footer
	$footerCode = '';
	if(function_exists('Testing_table_footer')) {
		$args = [];
		$footerCode = Testing_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
